Repository bentshrimp/GrowthHacking, pull requests merged in 2023-07, with the labels that each got.

#4 Security HOTFIX
  adService/adService/settings.py
Labels: security

#6 ✨ Add: insert user event into db
  fraud_detect_server/detect/views.py
  fraud_detect_server/fraud_detect_server/settings.py
Labels: feat

#9 코드 간결화 작업 완료
  ad_manage_server/ad_manage/templates/manager_platform.html
Labels: feat

#10 Feat/get ads from ad db
  ad_manage_server/ad_manage/urls.py
  ad_manage_server/ad_manage/views.py
Labels: enhancement

#12 🩹 Fix: import skipped models
  ad_manage_server/ad_manage/views.py
Labels: feat

#13 ✨ Add: delete ad
  ad_manage_server/ad_manage/urls.py
  ad_manage_server/ad_manage/views.py
Labels: feat
